/**
 * Mock Data - Datos de ejemplo para desarrollo
 * 
 * IMPORTANTE: Este archivo contiene datos de prueba adaptados al formato del backend.
 * En producción, estos datos vendrán del backend Spring Boot.
 */

import { Product, Category } from '@/types/models';
import helmetImg from '@/assets/placeholder-helmet.jpg';
import glovesImg from '@/assets/placeholder-gloves.jpg';

export const mockCategories: Category[] = [
  { id: 1, name: 'Cascos', slug: 'cascos' },
  { id: 2, name: 'Guantes', slug: 'guantes' },
  { id: 3, name: 'Chaquetas', slug: 'chaquetas' },
  { id: 4, name: 'Maletas y Baúles', slug: 'maletas' },
  { id: 5, name: 'Escapes', slug: 'escapes' },
  { id: 6, name: 'Protecciones', slug: 'protecciones' },
];

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Casco Integral Racing Pro X1',
    details: 'Casco integral de alto rendimiento con aerodinámica optimizada. Calota de fibra de carbono ultra ligera. Sistema de ventilación avanzado con 7 entradas y 4 salidas de aire. Interior antibacteriano extraíble y lavable. Homologación ECE 22.06.',
    specifications: '{"Material":"Fibra de carbono","Peso":"1350g","Homologación":"ECE 22.06","Ventilación":"7 entradas / 4 salidas"}',
    originalPrice: 449.99,
    sellPrice: 349.99,
    discount: 22,
    currency: 'EUR',
    shippingCost: 0,
    deliveryEstimateDays: '2-4 días',
    variant: '[{"groupName":"Talla","options":[{"value":"XS","extraPrice":0.0},{"value":"S","extraPrice":0.0},{"value":"M","extraPrice":0.0},{"value":"L","extraPrice":0.0},{"value":"XL","extraPrice":0.0}]},{"groupName":"Color","options":[{"value":"Negro","extraPrice":0.0},{"value":"Rojo","extraPrice":10.0},{"value":"Blanco","extraPrice":0.0}]}]',
    sellerName: 'AGV',
    category: 1,
    images: [helmetImg, helmetImg, helmetImg],
    averageRating: 4.5,
    reviewCount: 28
  },
  {
    id: 2,
    name: 'Guantes Racing Carbon Tech',
    details: 'Guantes deportivos con protecciones de carbono en nudillos. Palma de piel de canguro para máximo tacto. Costuras reforzadas en zonas de alto impacto. Cierre micrométrico ajustable. Certificación CE nivel 1.',
    specifications: '{"Material":"Piel de canguro + Carbono","Certificación":"CE nivel 1","Protecciones":"Nudillos, dedos, palma"}',
    originalPrice: 169.99,
    sellPrice: 129.99,
    discount: 24,
    currency: 'EUR',
    shippingCost: 0,
    deliveryEstimateDays: '2-4 días',
    variant: '[{"groupName":"Talla","options":[{"value":"S","extraPrice":0.0},{"value":"M","extraPrice":0.0},{"value":"L","extraPrice":0.0},{"value":"XL","extraPrice":0.0}]},{"groupName":"Color","options":[{"value":"Negro","extraPrice":0.0},{"value":"Blanco/Negro","extraPrice":5.0}]}]',
    sellerName: 'Alpinestars',
    category: 2,
    images: [glovesImg, glovesImg],
    averageRating: 4.7,
    reviewCount: 45
  },
  {
    id: 3,
    name: 'Casco Modular Urban Flip',
    details: 'Casco modular versátil para uso urbano y touring. Pantalla solar retráctil integrada. Sistema de apertura con una sola mano. Interior confortable con tejido hipoalergénico. Preparado para intercomunicador Bluetooth. Homologación P/J.',
    specifications: '{"Material":"Policarbonato","Homologación":"P/J","Pantalla solar":"Retráctil integrada","Bluetooth":"Preparado"}',
    originalPrice: 299.99,
    sellPrice: 249.99,
    discount: 17,
    currency: 'EUR',
    shippingCost: 0,
    deliveryEstimateDays: '2-4 días',
    variant: '[{"groupName":"Talla","options":[{"value":"XS","extraPrice":0.0},{"value":"S","extraPrice":0.0},{"value":"M","extraPrice":0.0},{"value":"L","extraPrice":0.0}]}]',
    sellerName: 'Shoei',
    category: 1,
    images: [helmetImg],
  },
  {
    id: 4,
    name: 'Guantes Touring Waterproof',
    details: 'Guantes impermeables para largas distancias. Membrana Gore-Tex garantiza impermeabilidad y transpirabilidad. Protecciones certificadas en nudillos y palma. Puño largo para máxima protección. Reflectantes para visibilidad nocturna.',
    specifications: '{"Material":"Gore-Tex + Cuero","Impermeabilidad":"100%","Certificación":"CE"}',
    originalPrice: 189.99,
    sellPrice: 159.99,
    discount: 16,
    currency: 'EUR',
    shippingCost: 0,
    deliveryEstimateDays: '2-4 días',
    variant: '[{"groupName":"Talla","options":[{"value":"M","extraPrice":0.0},{"value":"L","extraPrice":0.0},{"value":"XL","extraPrice":0.0}]}]',
    sellerName: 'Dainese',
    category: 2,
    images: [glovesImg],
  },
  {
    id: 5,
    name: 'Casco Jet Vintage Retro',
    details: 'Casco jet de estilo retro con diseño vintage. Calota en policarbonato de alta resistencia. Interior de ante sintético premium. Visera incluida. Sistema de cierre micrométrico. Perfecto para motos custom y café racer.',
    specifications: '{"Material":"Policarbonato","Estilo":"Vintage","Visera":"Incluida"}',
    originalPrice: 199.99,
    sellPrice: 169.99,
    discount: 15,
    currency: 'EUR',
    shippingCost: 0,
    deliveryEstimateDays: '2-4 días',
    variant: '[{"groupName":"Talla","options":[{"value":"S","extraPrice":0.0},{"value":"M","extraPrice":0.0},{"value":"L","extraPrice":0.0}]}]',
    sellerName: 'Bell',
    category: 1,
    images: [helmetImg],
  },
  {
    id: 6,
    name: 'Guantes Invierno Heated',
    details: 'Guantes calefactables para invierno extremo. Sistema de calefacción eléctrica con 3 niveles de temperatura. Batería de litio recargable (autonomía 6h). Membrana impermeable. Aislamiento térmico Thinsulate. Pantalla táctil compatible.',
    specifications: '{"Calefacción":"3 niveles","Batería":"Litio 6h","Compatibilidad":"Pantalla táctil"}',
    originalPrice: 249.99,
    sellPrice: 199.99,
    discount: 20,
    currency: 'EUR',
    shippingCost: 0,
    deliveryEstimateDays: '3-5 días',
    variant: '[{"groupName":"Talla","options":[{"value":"M","extraPrice":0.0},{"value":"L","extraPrice":0.0},{"value":"XL","extraPrice":0.0}]}]',
    sellerName: 'Macna',
    category: 2,
    images: [glovesImg],
  },
  {
    id: 7,
    name: 'Casco Off-Road MX Elite',
    details: 'Casco cross/enduro de competición. Diseño aerodinámico con sistema EPS multi-densidad. Visera ajustable y extraíble. Preparado para gafas de motocross. Ventilación superior con 9 canales de aire. Peak solar incluido.',
    specifications: '{"Tipo":"Off-Road","EPS":"Multi-densidad","Ventilación":"9 canales"}',
    originalPrice: 329.99,
    sellPrice: 279.99,
    discount: 15,
    currency: 'EUR',
    shippingCost: 0,
    deliveryEstimateDays: '2-4 días',
    variant: '[{"groupName":"Talla","options":[{"value":"S","extraPrice":0.0},{"value":"M","extraPrice":0.0},{"value":"L","extraPrice":0.0},{"value":"XL","extraPrice":0.0}]}]',
    sellerName: 'Fox Racing',
    category: 1,
    images: [helmetImg],
  },
  {
    id: 8,
    name: 'Guantes Verano Mesh Pro',
    details: 'Guantes ultraligeros de verano con máxima ventilación. Construcción en malla técnica transpirable. Protecciones certificadas ultradelgadas. Palma reforzada con material sintético de alto agarre. Nudillos flexibles para máxima libertad.',
    specifications: '{"Material":"Malla técnica","Estación":"Verano","Ventilación":"Máxima"}',
    originalPrice: 79.99,
    sellPrice: 59.99,
    discount: 25,
    currency: 'EUR',
    shippingCost: 0,
    deliveryEstimateDays: '2-4 días',
    variant: '[{"groupName":"Talla","options":[{"value":"S","extraPrice":0.0},{"value":"M","extraPrice":0.0},{"value":"L","extraPrice":0.0}]},{"groupName":"Color","options":[{"value":"Negro","extraPrice":0.0},{"value":"Gris","extraPrice":0.0}]}]',
    sellerName: 'Revit',
    category: 2,
    images: [glovesImg],
  },
];
